manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: LondoLeo
      url-base: https://github.com/LondoLeo
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboards-splaytoraid40
      remote: LondoLeo
      revision: main
  self:
    path: config
